language: python
python:
   - "2.7_with_system_site_packages"

addons:
   apt:
      packages:
         - libhdf5-serial-dev
         - netcdf-bin
         - libnetcdf-dev

before_install:
   - "export DISPLAY=:99.0"
   - "sh -e /etc/init.d/xvfb start"
   - sudo apt-get update -qq

install:
   - pip install -r requirements.txt
   - sudo python setup.py build
   - sudo python setup.py install

script:
   - pip install coveralls pep8
   - nosetests -v --with-coverage --cover-erase --cover-package=wxgen

after_success:
   - coveralls

env:
 - DIST=trusty

os: linux
